# Generated by Django 2.2.9 on 2021-12-22 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20211214_1848'),
    ]

    operations = [

        
    ]
