# Generated by Django 2.2.9 on 2021-12-22 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_profile'),
    ]

    operations = [

    ]
