# Generated by Django 2.2.6 on 2021-12-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211223_0158'),
    ]

    operations = [

    ]
